import type { NextPage } from "next";

import Head from "next/head";

import useScrollPosition from "../hooks/useScrollPosition";

import ScrollToTop from "../components/ScrollToTop";
import { useState } from "react";

const Home: NextPage = () => {
  const scrollPosition = useScrollPosition();

  const navconfig = {
    bgClass: " bg-transaprent h-44",
    scrolledBgClass:
      "bg-violet-600 bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-40 h-24",
  };

  return (
    <div className="antialiased">
      <Head>
        <title>Saurav </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className={`flex items-center justify-between  fixed w-full transition-all ease-in-out duration-300 ${
          scrollPosition > 50 ? navconfig.scrolledBgClass : navconfig.bgClass
        } `}
      >
        <div className="flex items-center justify-between w-full max-w-6xl m-auto ">
          <a className="text-3xl font-bold text-white">Saurav Sidharthan</a>
          <nav className="text-white">
            <ul className="relative left-0 right-0 flex space-x-6">
              <li>Home</li>
              <li>About</li>
              <li>Contact</li>
              <li>Resume</li>
            </ul>
          </nav>
        </div>
      </header>
      <main>
        <section className="min-h-screen px-8 pt-32 pb-16 bg-violet-900 md:px-12">
          <div className="max-w-6xl mx-auto md:flex md:items-center md:justify-between">
            <div className="md:flex-1 md:mr-6">
              <h1 className="text-4xl font-bold leading-tight text-white md:text-5xl">
                Hello I'am Saurav
              </h1>
              <p className="mt-4 text-lg text-white">
                I'am a Freelance web3 developer based out of Bangalore, India.
              </p>
            </div>
            <div className="md:flex-1">
              <img
                src="https://res.cloudinary.com/thirus/image/upload/v1632162912/logos/chat_ys7mog.svg"
                alt="Chat with loved ones"
              />
            </div>
          </div>
        </section>
        <section className="min-h-screen px-8 pt-32 pb-16 bg-violet-900 md:px-12">
          <div className="max-w-6xl mx-auto md:flex md:items-center md:justify-between">
            <div className="md:flex-1 md:mr-6">
              <h1 className="text-4xl font-bold leading-tight text-white md:text-5xl">
                Hello I'am Saurav
              </h1>
              <p className="mt-4 text-lg text-white">
                I'am a Freelance web3 developer based out of Bangalore, India.
              </p>
            </div>
            <div className="md:flex-1">
              <img
                src="https://res.cloudinary.com/thirus/image/upload/v1632162912/logos/chat_ys7mog.svg"
                alt="Chat with loved ones"
              />
            </div>
          </div>
        </section>
        <section id="features" className="min-h-screen"></section>
        <section id="about" className="min-h-screen bg-gray-100"></section>
        <section id="contact" className="min-h-screen"></section>
        {/* <section
          style={{
            height: "1200px",
          }}
          className="max-h-screen bg-cover bg-violet-900"
        >
          <p className="text-5xl ">Hi! Iam Saurav, web3 developer</p>
        </section> */}
      </main>

      <footer className="w-full bg-blue-700">
        <div className="flex items-center justify-center h-20 m-auto">
          <p className="text-white">Copyright 2022. Saurav</p>
        </div>
      </footer>
      <ScrollToTop />
    </div>
  );
};

export default Home;
